name: Run Shell Script

on:
  push:
    branches: [ master ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shell script
        run: bash main.sh.txt 1
